"""add digital land tables

Revision ID: 6e2af83d8842
Revises: 882a26822214
Create Date: 2022-06-17 17:47:43.714261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e2af83d8842"
down_revision = "882a26822214"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("collection", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("collection"),
    )
    op.create_table(
        "issue_type",
        sa.Column("issue_type", sa.Text(), nullable=False),
        sa.Column("issue_name", sa.Text(), nullable=False),
        sa.Column("issue_description", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("severity_name", sa.Text(), nullable=False),
        sa.Column("severity_description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("issue_type"),
    )
    op.create_table(
        "resource",
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("resource"),
    )
    op.create_table(
        "dataset",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("collection_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.collection"],
        ),
        sa.PrimaryKeyConstraint("dataset"),
    )
    op.create_table(
        "organisation_resource",
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisation.organisation"],
        ),
        sa.ForeignKeyConstraint(
            ["resource"],
            ["resource.resource"],
        ),
        sa.PrimaryKeyConstraint("organisation", "resource"),
    )
    op.create_table(
        "dataset_resource",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset"],
            ["dataset.dataset"],
        ),
        sa.ForeignKeyConstraint(
            ["resource"],
            ["resource.resource"],
        ),
        sa.PrimaryKeyConstraint("dataset", "resource"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset_resource")
    op.drop_table("organisation_resource")
    op.drop_table("dataset")
    op.drop_table("resource")
    op.drop_table("issue_type")
    op.drop_table("collection")
    # ### end Alembic commands ###
